name: FanTp
version: '1.2.0'
main: top.eatfan.fanTp.FanTp
authors: [ EatFan ]
api-version: 1.13
description: A simpler and faster player teleportation plug-in

commands:
  tpa:
    description: main command
    usage: /tpa
  t:
    description: main command
    usage: /t
  fantp:
    description: main command
    usage: /fantp

permissions:
  fantp.admin:
    description: This is admin permission in the plugin
  fantp.tp:
    description: This is the tp permission in the plugin

