name: FanTp
version: '1.0.0'
main: top.eatfan.fanTp.FanTp
authors: [ EatFan ]
description: A simpler and faster player teleportation plug-in

commands:
  tpa:
    description: main command
    usage: /tpa
  t:
    description: main command
    usage: /t